#!/usr/bin/env bash

# goes up the directory tree by $# amount
up()
{
  local var
  if [[ "$#" -lt 1 ]]; then
    cd ..
  else
    var=""
    for ((i=0; i<$1; i++)); do
      var="../$var"
    done
    cd "$var" || exit
  fi
}

# colorizing man-pages
man()
{
  env LESS_TERMCAP_mb=$'\e[36m'  \
  LESS_TERMCAP_md=$'\e[36m'    \
  LESS_TERMCAP_me=$'\e[0m'    \
  LESS_TERMCAP_se=$'\e[0m'    \
  LESS_TERMCAP_so=$'\e[1m'    \
  LESS_TERMCAP_ue=$'\e[0m'    \
  LESS_TERMCAP_us=$'\e[31m'    \
  man "$@"
}

# swap two files
swap()
{
  local TMPFILE=$(mktemp)
  mv "$1" "$TMPFILE"
  mv "$2" "$1"
  mv "$TMPFILE" "$2"
  rm "$TMPFILE"
}

# archiving to make funny named files
archive()
{
  local file
  file="$1.old"
  if [ ! -f "$1" ]; then
    echo "$1 doesn't exist"
    return 1
  fi
  while [ -f "$file" ]; do
    file="$file.old"
  done
  echo "Archived to : $file"
  mv "$1" "$file"
}

# automatic symlinking
# archive the old file if exists
soft_force_symlink()
{
  if [ ! -f "$2" ]; then
    ln -s "$1" "$2"
    return $?
  fi
  if [ -n "$(diff --brief "$2" "$1")" ]; then
    archive "$2"
  fi
  ln -sf "$1" "$2"
}
