export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="λ"

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

export EDITOR="vim"

PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$HOME/.cargo/bin"
PATH="$PATH:$HOME/.npm/modules/bin"

export PATH
