export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="λ"

plugins=()

source $ZSH/oh-my-zsh.sh

N_PREFIX="$HOME/.local/n"

PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$N_PREFIX/bin"
PATH="$PATH:$HOME/.cargo/bin"

export PATH
export N_PREFIX
export EDITOR="vim"
