#!/usr/bin/env bash

wallpaper=/tmp/wallpapers/wallpaper
converted=$wallpaper
current=/tmp/wallpapers/current

vol=$(pamixer --get-volume)
#vol=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 2 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

# create the file path
mute=false
#if [[ $(pamixer --get-mute) == true ]]; then
#	converted=$converted"_mute"
#	mute=true
#else
#	converted=$converted"_vol_"$vol
#fi

vpn=true
if [[ -n $(pgrep openvpn) || -n $(pgrep pptp) ]]; then
	converted=$converted"_vpn"
	vpn=true
fi

blur=false
focused_desktop=$(bspc query -D -d)
if [[ -n $(bspc query -N -d $focused_desktop) ]]; then
	converted=$converted"_blur"
	blur=true
fi

battery=false
bat=$(acpi | cut -d " " -f 4  | sed 's/[^0-9]//g')
#bat=30
battery_amount=$(($bat / 25 * 25))
if [[ $(acpi | cut -d " " -f 3) == *Discharging* ]]; then
	if [[ "$bat" -lt "40" ]]; then
		converted=$converted"_battery_"$battery_amount
		battery=true
	fi
fi

if [[ -f $current && $(cat $current) == $converted ]]; then
	exit
fi

#status_wifi=true
#if [[ $status_wifi = "disabled" ]]; then
#	converted=$converted"_wifi"
#	status_wifi=false
#fi

echo $converted > $current

# create the file, if it isn't cached
if [[ ! -f $converted ]]; then
	convert_cmd="convert $wallpaper"
#	if [[ $mute == true ]]; then
#		convert_cmd=$convert_cmd" -fill navyblue -colorize 60"
#		convert_cmd=$convert_cmd" -fill black -colorize 50"
#	else
#		amount=$(((100 - vol) / 2))
#		convert_cmd=$convert_cmd" -fill blue -colorize $amount"
#		convert_cmd=$convert_cmd" -fill black -colorize $amount"
#	fi

#	if [[ $vpn == false ]]; then
#		convert_cmd=$convert_cmd" -fill red -colorize 50"
#	fi

	if [[ $blur == true ]]; then
		convert_cmd=$convert_cmd" -blur 0x5"
	fi

#	if [[ $battery == true ]]; then
#		battery_amount=$(((100 - $battery_amount) - 20))
#		convert_cmd=$convert_cmd" /home/erelde/Pictures/circuit-imprime-red-trans.png -compose blend -define compose:args="$battery_amount" -gravity center -composite"
#	fi

	$convert_cmd $converted
fi

feh --bg-scale --no-xinerama $converted

# vim: noai:ts=4:sw=4
