#!/usr/bin/env bash
# shellcheck disable=SC1090
# shellcheck disable=SC2016

# Stop if not interactive mode
case $- in
  *i*) ;;
    *) return;;
esac

HISTSIZE=1000
HISTFILESIZE=2000
# Don't log duplicate
HISTCONTROL=ignoreboth
# Append to histfile, don't overwrite
shopt -s histappend

# Update LINES and COLUMNS after each command
shopt -s checkwinsize

declare -ra libs=(
  "alias.sh"
  "function.sh"
  "gh.sh"
  "theme.sh"
)

# Load aliases and functions
for lib in "${libs[@]}"; do
  source "$HOME/.config/bash/$lib"
done

# Custom keybindings
bind -x '"\C-n":"goto_project"'
bind -x '"\C-k":"git_log_pager_short"'

# Enable variables in prompt
shopt -s promptvars

test -f ~/.env && . ~/.env # if environment overwrite previous settings
