#!/usr/bin/env bash

sxhkd &
gnome-keyring-daemon --start --daemonize &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 1
bspc config window_gap 28
bspc config split_ratio 0.5
bspc config click_to_focus true
bspc config initial_polarity second_child

feh --bg-fill "$BSPWM_BG"
