#!/usr/bin/env python3

import json
import sys
from urllib.request import urlopen


def get(url):
    return json.loads(urlopen(url).read())


def names(data):
    yield from (repo["name"] for repo in data)


def pprint(names):
    print("\n".join(names))


if __name__ == "__main__":
    pprint(
        names(
            get(f"https://api.bitbucket.org/2.0/repositories/{sys.argv[1]}")["values"]
        )
    )
