#!/usr/bin/env python3

import argparse
import json
import subprocess
import sys


def main(args):
    crate = json.load(
        subprocess.Popen(("cargo", "read-manifest"), stdout=subprocess.PIPE).stdout
    )
    subprocess.call(
        (
            "cargo",
            "test",
            "--package",
            crate["name"],
            "--lib",
            "--",
            "::".join(args.testpath),
            "--nocapture",
        )
    )


def parse_args(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("testpath", nargs="+")
    return parser.parse_args(argv)


if __name__ == "__main__":
    main(parse_args(sys.argv[1:]))
