#!/usr/bin/env python3

import argparse
import subprocess
import sys


def main(args):
    files, insertions, deletions = parse(git_stats(args.author, args.branch))
    out = [
        f"{args.author} on {args.branch}",
        f"{files} files changed, {insertions} insertions(+), {deletions} deletions(-)",
    ]
    print("\n".join(out))
    return 0


def git_stats(author, branch="master"):
    git = ["git", "log", f"--author={author}", "--shortstat", "--format=", branch]
    return subprocess.check_output(git, universal_newlines=True)


def parse(text):
    value = lambda l, i: int(l[i]) if len(l) > i else 0
    files, insertions, deletions = [], [], []
    for line in text.split("\n"):
        token = line.split()
        files.append(value(token, 0))
        insertions.append(value(token, 3))
        deletions.append(value(token, 5))
    return sum(files), sum(insertions), sum(deletions)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("author")
    parser.add_argument("branch", nargs="?", default="master")
    sys.exit(main(parser.parse_args()))
