#!/usr/bin/env bash

set -e

branch()
{
  git branch 2>/dev/null | grep -e '^*' | tr -d '\* '
}

ensure_valid_ref()
{
  ref=$1
  (
    set +e
    git show-ref $ref > /dev/null
    if [[ $? == 1 ]]; then
      echo "$0: bad ref: $ref"
      exit 1
    fi
  )
}

show_rev()
{
  rev=$1
  git -c color.ui=always log --graph --all --pretty='%Cred%h%Creset %Cgreen%cr %Cblue%an%Creset %s%C(yellow)%d%Creset' -1 $rev
  git diff $rev^..$rev | diffstat -C
  echo
}

(
  if [[ $# == 2 ]]; then
    LOCAL=$1
    REMOTE=$2
  elif [[ $# == 1 ]]; then
    LOCAL=`branch`
    REMOTE=$1
  else
    LOCAL=`branch`
    REMOTE=origin/$LOCAL
  fi

  ensure_valid_ref $LOCAL
  ensure_valid_ref $REMOTE

  echo "changes from local ${LOCAL} to remote ${REMOTE}:"
  echo

  echo incoming:
  echo
  for rev in `git rev-list $LOCAL..$REMOTE`; do
    show_rev $rev
  done

  echo outgoing:
  echo
  for rev in `git rev-list $REMOTE..$LOCAL`; do
    show_rev $rev
  done
) | less
