#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys
import textwrap


def main(parser: argparse.ArgumentParser):
    args, argv = parser.parse_known_args(sys.argv[1:])
    if args.alias is None:
        parser.print_help()
        return 0
    return subprocess.run(["git"] + args.alias + argv, cwd=args.repository).returncode


def build_parser(workdir: str):
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent(
            """
            Script meant to interact with a git repository used as a journal.
            Set the environment variable 'JOURNAL_REPO' to a path pointing
            to a git repository which will be used as the journal.
            """
        ),
        epilog=textwrap.dedent(
            """
            usage examples:

              alias journal=git-journal
              journal entries --after=2019
              journal read <shasum>
              journal read --before=2017
            """
        ),
    )
    parser.set_defaults(alias=None)
    parser.add_argument(
        "-r",
        "--repository",
        metavar="path",
        default=workdir,
        help="override the JOURNAL_REPO environment variable",
    )
    subparsers = parser.add_subparsers(required=False, description="")
    read = subparsers.add_parser("read", help="use to read the whole journal")
    read.set_defaults(alias=["log"])
    entries = subparsers.add_parser("entries", help="list the journal entries")
    entries.set_defaults(
        alias=[
            "log",
            "--date=short",
            "--format=%C(red)%h%Creset %C(green)%ad%Creset %s",
        ]
    )
    # depends on my other script `git-nav-log`
    nav_entries = subparsers.add_parser(
        "nav-entries", help="navigate the journal entries"
    )
    nav_entries.set_defaults(alias=["nav-log"])
    write = subparsers.add_parser("write", help="write a new entry")
    write.set_defaults(alias=["commit", "--allow-empty"])
    backup = subparsers.add_parser("backup", help="sync the new entries")
    backup.set_defaults(alias=["push"])
    return parser


if __name__ == "__main__":
    try:
        workdir = os.environ["JOURNAL_REPO"]
    except KeyError:
        exit(
            "Set the environment variable 'JOURNAL_REPO' to a path pointing "
            "to a git repository which will be used as a journal."
        )
    exit(main(build_parser(workdir)))
