#!/usr/bin/env python3

import os
import sys
import subprocess


ALIAS = {
    'read': ['log'],
    'pages': ['log', '--date=short', '--format=%C(red)%h%Creset %C(green)%ad%Creset %s'],
    'write': ['commit', '--allow-empty'],
    'save': ['push'],
}

try:
    WORKDIR = os.environ['JOURNAL_REPO']
except KeyError:
    WORKDIR = os.path.join(os.environ['HOME'], 'log')

GITDIR = os.path.join(WORKDIR, '.git')


def usage():
    text = [
        f'Usage: {os.path.basename(__file__)} <git subcommand>',
        'Aliases added by this scripts:',
    ]
    for alias, command in ALIAS.items():
        text.append(f'  {alias:<6}: {" ".join(command)}')
    print('\n'.join(text))


def git_command(sub: list):
    git = ['git',  '--git-dir', GITDIR, '--work-tree', WORKDIR]
    subprocess.call(git + sub)


def main(argv):
    args = argv[1:]
    if argv[1] in ALIAS:
        args = ALIAS[argv[1]] + argv[2:]
    git_command(args)


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] == 'help':
        usage()
        exit(0)
    main(sys.argv)
