#!/usr/bin/env bash

set -euo pipefail

find_git_unknowns() {
  git status --porcelain=v1 |
    grep -e "^??" |
    sed 's/^?? //g'
}

find_git_unknowns | while IFS=$'\n' read -r file; do
  rm -rf "$file"
done
