#!/usr/bin/env bash
# when piped this will output a csv
# else it will be presented as a table

if [ -t 1 ] && [ "$*" == "" ]; then
  git-report.py | sort -h | column -s ';' -t
else
  git-report.py $*
fi
