#!/usr/bin/env bash
# when piped this will output a csv
# else it will be presented as a table

main()
{
  IFS=$'\n'
  echo "files;insertions;deletions;author;branch"
  for author in $(git authors $*); do
    git insertions "$author" $*
  done | sort -h
}

if [ -t 1 ]; then
  main "$@" | column -s ";" -t
else
  main "$@"
fi
