#!/usr/bin/env bash


log()
{
  git -c color.ui=always log --oneline
}

fzf_preview()
{
  local git_cmd
  git_cmd="git -c color.ui=always show --stat"
  fzf --ansi --no-mouse --preview="$git_cmd {+1}"
}


log | fzf_preview | cut -d ' ' -f 1
