#!/usr/bin/env python3

import argparse
import json
import os
import sys
from urllib.request import urlopen, Request


def main(args):
    print("\n".join(user_repos(args.user)))


def user_repos(user):
    repos = f"https://api.github.com/users/{user}/repos"
    return (repo["name"] for repo in api_get(repos))


def api_get(url):
    r = Request(url)
    if "GITHUB_API_TOKEN" in os.environ:
        token = os.environ["GITHUB_API_TOKEN"]
        r.add_header("Authorization", f"token {token}")
    return json.loads(urlopen(r).read())


def args(argv=sys.argv[1:]):
    p = argparse.ArgumentParser(description="Get the user's public repos")
    p.add_argument("user")
    return p.parse_args(argv)


if __name__ == "__main__":
    try:
        sys.exit(main(args()))
    except KeyboardInterrupt:
        print()
