#!/usr/bin/env python3

"""journal

Use a git repository as a journal.
Each commit is a journal entry.
The actual repository could contain no files.

This script mostly only exists to be able to write to
the journal from anywhere and add some semantic aliases like:
  journal write
  journal entries
  journal read

All of those can be completed by any valid git options
for the command it's aliasing:
  journal write -m "a quick passing thought"
  journal read --reverse --after=2017 --before=2018-02-03
"""

import argparse
import os
import subprocess
import textwrap


def main(parser: argparse.ArgumentParser):
    args, argv = parser.parse_known_args()
    if args.action is None:
        parser.print_help()
        return 0
    return args.action(args, argv)


def journal(func):
    def inner(args, argv):
        command = ["git"] + func(args, argv)
        process = subprocess.run(command, cwd=args.repository)
        return process.returncode

    return inner


@journal
def read(args, argv):
    if args.ref is None:
        return ["log"] + argv
    return ["show", "--shortstat", args.ref] + argv


@journal
def entries(args, argv):
    return [
        "log",
        "--date=short",
        "--format=%C(red)%h%Creset %C(green)%ad%Creset %s",
    ] + argv


@journal
def nav_entries(args, argv):
    return ["nav-log"] + argv


@journal
def write(args, argv):
    return ["commit", "--allow-empty"] + argv


@journal
def backup(args, argv):
    return ["push"] + argv


def build_parser(workdir: str):
    def program_is_available(program):
        def is_exe(path):
            return os.path.isfile(path) and os.access(path, os.X_OK)

        return any(
            is_exe(os.path.join(path, program))
            for path in os.environ["PATH"].split(os.pathsep)
        )

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent(
            """
            Script meant to interact with a git repository used as a journal.
            Set the environment variable 'JOURNAL_REPO' to a path pointing
            to a git repository which will be used as the journal.
            """
        ),
        epilog=textwrap.dedent(
            """
            usage examples:
              journal entries --after=2019
              journal read <shasum>
              journal write -m "a quick passing thought"
              journal read --reverse --after=2017 --before=2018-02-03
            """
        ),
    )
    parser.set_defaults(action=None)
    parser.add_argument(
        "-r",
        "--repository",
        metavar="path",
        default=workdir,
        help="override the JOURNAL_REPO environment variable",
    )
    subparsers = parser.add_subparsers(
        description="can be completed by any valid git options for the command it's aliasing",
    )

    def add_subcommand(name, *, help, aliases, action):
        sub = subparsers.add_parser(name, help=help, aliases=aliases)
        sub.set_defaults(action=action)
        return sub

    add_subcommand(
        "read",
        help="use to read the whole journal [log|show]",
        aliases=["r"],
        action=read,
    ).add_argument("ref", help="commit reference", nargs="?")
    add_subcommand(
        "entries", help="list the journal entries [log]", aliases=["e"], action=entries
    )
    # depends on my other script `git-nav-log` and `fzf`
    if all(map(program_is_available, ["git-nav-log", "fzf"])):
        add_subcommand(
            "nav-entries",
            help="navigate the journal entries [git-nav-log]",
            aliases=["n"],
            action=nav_entries,
        )
    add_subcommand(
        "write", help="write a new entry [commit]", aliases=["w"], action=write
    )
    add_subcommand(
        "backup", help="sync the new entries [push]", aliases=["b"], action=backup
    )
    return parser


if __name__ == "__main__":
    try:
        workdir = os.environ["JOURNAL_REPO"]
    except KeyError:
        exit(
            "Set the environment variable 'JOURNAL_REPO' to a path pointing "
            "to a git repository which will be used as a journal."
        )
    exit(main(build_parser(workdir)))
