#!/usr/bin/env bash
#/ install a python executable with pip in a virtualenv
#/ and writes a wrapper script to make it available globally
usage()
{
  echo "usage: $(basename "$0") package [executable]"
  grep "^#/" "$0" | cut -c4-
  exit 0
}

base_path="$HOME/.venv"

main()
{
  local package executable
  package="$1"
  executable=${2:-"$package"}
  make_virtualenv "$package"
  write_wrapper "$package" "$executable"
}

make_virtualenv()
{
  local package
  package="$1"
  python3 -m venv "$base_path/$package"
  source "$base_path/$package/bin/activate"
  pip install "$package"
}

write_wrapper()
{
  local executable package
  package="$1"
  executable="$2"
  cat > "$HOME/.local/bin/$executable" <<- WRAPPER_SCRIPT
#!/usr/bin/env bash

source "$base_path/$package/bin/activate"
$base_path/$package/bin/$executable \$*
WRAPPER_SCRIPT
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  if [ $# -lt 1 ]; then
    usage
  fi
  main "$@"
fi
