#!/usr/bin/env bash


fzf_preview()
{
  local bat_cmd
  bat_cmd="bat --color always --theme OneHalfDark --plain"
  fzf --ansi --preview="$bat_cmd {}"
}

loop()
{
  local file
  while file=$(fzf_preview); do
    vi "$file"
  done
}

loop
