#!/usr/bin/env bash


# Environment variables :
N_PREFIX="$HOME/.local/n"


prepend:path()
{
  if [ -d "$1" ]; then
    PATH="$1:$PATH"
  fi
}

prepend:path "$HOME/.cargo/bin"
prepend:path "$HOME/.gem/ruby/2.5.0/bin"
prepend:path "$N_PREFIX/bin"
prepend:path "$HOME/.local/bin"
prepend:path "$HOME/.bin"
unset -f prepend:path

EDITOR="$(command -v nvim)"

export N_PREFIX
export PATH
export EDITOR
